import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { getStrapiEndpoint } from "@/lib/strapi";
import { getStrapiData, getFullImageUrl } from "@/utils/strapi-helper";
import "./globals.css";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type NavPage = {
  id?: number;
  Label?: string;
  slug?: string;
};

type LayoutData = {
  theme?: {
    Name?: string;
    CssPath?: string;
  };
  Logo?: any;
  Favicon?: any;
};

async function getLayoutData(strapiEndpoint: ReturnType<typeof getStrapiEndpoint>) {
  try {
    const layoutDataResponse = await getStrapiData(strapiEndpoint, "layout-data", {
      populate: {
        theme: true,
        Logo: true,
        Favicon: true,
      }
    });

    return (layoutDataResponse?.data as LayoutData | undefined) ?? undefined;
  } catch {
    return undefined;
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const strapiEndpoint = getStrapiEndpoint();

  let navItems: { label: string; href: string }[] = [
    { label: "Home", href: "/" },
  ];

  let logo = "";
  let themeCssPath = "";

  try {
    const tasks: Promise<any>[] = [
      getStrapiData(strapiEndpoint, "nav-bar", {
        populate: {
          pages: true,
        },
      }),
      getLayoutData(strapiEndpoint)
    ];
    const [navBarData, layoutData] = await Promise.all(tasks);

    const pages: NavPage[] = navBarData?.data?.pages ?? [];

    navItems = [
      { label: "Home", href: "/" },
      ...pages
        .filter((page) => page?.Label && page?.slug)
        .map((page) => ({
          label: page.Label as string,
          href: `/page/${page.slug}`,
        })),
      { label: "Blog", href: "/blog" },
    ];

    if (layoutData?.Logo) {
      logo = getFullImageUrl(layoutData.Logo, strapiEndpoint) || "";
    }

    if (layoutData?.theme?.CssPath) {
      themeCssPath = layoutData.theme.CssPath;
    }
  } catch {
    // keep fallback theme/logo
  }

  return (
    <html lang="en">
      <head>
        {themeCssPath ? <link rel="stylesheet" href={themeCssPath} /> : null}
      </head>
      <body>
        <Navbar navItems={navItems} logo={logo} />
        <main className="th-main">{children}</main>
      </body>
    </html>
  );
}