import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { getStrapiEndpoint } from "@/lib/strapi";
import { getStrapiData } from "@/utils/strapi-helper";
import "./globals.css";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type NavPage = {
  id?: number;
  Label?: string;
  slug?: string;
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const strapiEndpoint = getStrapiEndpoint();

  let navItems: { label: string; href: string }[] = [
    { label: "Home", href: "/" },
  ];

  try {
    const navBarData = await getStrapiData(strapiEndpoint, "nav-bar", {
      populate: [
        {
          field: "pages",
        },
      ],
    });

    console.log(navBarData);

    const pages: NavPage[] = navBarData?.data?.pages ?? [];

    navItems = [
      { label: "Home", href: "/" },
      ...pages
        .filter((page) => page?.Label && page?.slug)
        .map((page) => ({
          label: page.Label as string,
          href: `/page/${page.slug}`,
        })),
    ];
  } catch {
    // keep fallback navItems
  }

  return (
    <html lang="en">
      <head />
      <body>
        <Navbar navItems={navItems} />
        <main>{children}</main>
      </body>
    </html>
  );
}