import type { Metadata } from "next";
import Navbar from '@/components/Navbar';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { label: 'Home', href: '/' },
  { label: 'Login', href: '/login' }
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar navItems={navItems} />
        {children}
      </body>
    </html>
  );
}
